language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
    - php: hhvm
    - php: hhvm-nightly

# faster builds on new travis setup not using sudo
sudo: false

cache:
  directories:
    - vendor
    
before_script:
 - composer self-update
 - composer update --prefer-dist

script:
 - vendor/bin/php-cs-fixer fix src --level=psr2 --dry-run -vv
 - mkdir -p build/logs
 - ./vendor/bin/phpunit -c travis.phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  
