language: php

php:
  - 5.3
  - 5.5
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 7
    - php: hhvm-nightly

before_script:
 - composer update --prefer-dist

script:
 - vendor/bin/php-cs-fixer fix src --level=psr2 --dry-run -vv
 - mkdir -p build/logs
 - ./vendor/bin/phpunit -c travis.phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  
