language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true

# faster builds on new travis setup not using sudo
sudo: false

before_script:
 - composer self-update
 - composer update --prefer-source -n --verbose

script:
 - vendor/bin/php-cs-fixer fix src --level=psr2 --dry-run -vv
 - mkdir -p build/logs
 - ./vendor/bin/phpunit -c travis.phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  
